name: Push to Main

on:
  push:
    branches: [main]

permissions:
  contents: write
  deployments: write

jobs:
  cloudflare:
    uses: burnt-labs/github-workflows/.github/workflows/cloudflare-main.yml@e80433becb3bfbd429ade0815c8e012912190205 # v1.4.1
    secrets:
      cloudflare-account-id: ${{ secrets.BURNT_CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.BURNT_CLOUDFLARE_API_TOKEN }}
