name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  deployments: write

jobs:
  cloudflare:
    uses: burnt-labs/github-workflows/.github/workflows/cloudflare-release.yml@dc3c150483da96152a16d569ad735754033933cb # v1.1.0
    with:
      release-tag: ${{ github.event.release.tag_name }}
      release-url: ${{ github.event.release.html_url }}
      prerelease: ${{ github.event.release.prerelease }}
    secrets:
      cloudflare-account-id: ${{ secrets.BURNT_CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.BURNT_CLOUDFLARE_API_TOKEN }}
